#!/bin/sh

ADDONNAME=hm-iobroker
ADDONDIR=/usr/local/addons/${ADDONNAME}
WWWDIR=/usr/local/etc/config/addons/www/${ADDONNAME}
RCDDIR=/usr/local/etc/config/rc.d

start() {
    echo starting
}

stop() {
    echo stopping
}

case "$1" in

  ""|start)
    start
    ;;

  stop)
    stop
    ;;

  restart|reload)
    stop
    sleep 2
    start
    ;;

  info)
    echo "Info: <b>ioBroker Addon</b><br>"
    echo "Info: (c) 2016 Jens Maus<br>"
    echo "Info: <a href='http://github.com/jens-maus/hm-iobroker'>http://github.com/jens-maus/hm-iobroker</a>"
    echo "Version: $(cat ${WWWDIR}/VERSION)"
    echo "Name: hm-iobroker"
    echo "Operations: uninstall restart"
    echo "Config-Url: /addons/${ADDONNAME}/"
    echo "Update: /addons/${ADDONNAME}/update-check.cgi"
    ;;

  uninstall)
    # stop the service and deinstall the cronjob
    stop

    # remove the addon button
    ${ADDONDIR}/bin/update_addon hm-iobroker

    # remove the whole addon related stuff
    rm -rf ${ADDONDIR}
    rm -rf ${WWWDIR}
    rm -f ${RCDDIR}/${ADDONNAME}
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|info|uninstall}" >&2
    exit 1
    ;;

esac

exit 0
