#!/bin/sh

ADDONNAME=hm-iobroker
CONFIG_DIR=/usr/local/etc/config
ADDON_DIR=/usr/local/addons/${ADDONNAME}
RCD_DIR=${CONFIG_DIR}/rc.d
WWW_DIR=${CONFIG_DIR}/addons/www/${ADDONNAME}

# make sure this addon is only executed on
# supported platforms
if [ "$1" = "" ]; then
  lcdtool "CCU1 not supported... "
  exit 1
fi

# mount /usr/local if not already mounted
mount | grep /usr/local 2>&1 >/dev/null
if [ $? -eq 1 ]; then
  mount /usr/local
fi

# create necessary directories
mkdir -p ${ADDON_DIR}
chmod 755 ${ADDON_DIR}
mkdir -p ${RCD_DIR}
chmod 755 ${RCD_DIR}

# copy addon (common stuff)
cp -af common/* ${ADDON_DIR}/

# copy addon (CCU dependent stuff)
if [ "$1" = "CCU2" ]; then
  cp -af ccu2/* ${ADDON_DIR}/
elif [ "$1" == "HM-RASPBERRYMATIC" ]; then
  cp -af ccurm/* ${ADDON_DIR}/
fi

# copy startup script
cp -af rc.d/* ${RCD_DIR}

# copy www stuff
cp -af www ${ADDON_DIR}/
if [ ! -e ${WWW_DIR} ]; then
  ln -sf ${ADDON_DIR}/www ${WWW_DIR}
fi

# add menu entry
touch /usr/local/etc/config/hm_addons.cfg
${ADDON_DIR}/bin/update_addon hm-iobroker ${ADDON_DIR}/etc/hm-iobroker-addon.cfg

# synchronize filesystem before performing a reboot
# afterwards
sync
